### ISSUE TITLE
ToDo List to call it an App

### ISSUE THREAD

**Issue by fridlmue** [fridlmue/harbour-btvol#1]
This software is currently more a demo/proof of concept then a proper app.

At least the following needs to be fixed:

- [x] List current volume level or remove related texts.
- [x] List of devices is not filtered nicely. Not just hide objects in the List, but remove the "empty" elements from the list.
- [x] Add an App-Icon.
- [x] Short Info and License page with link to https://github.com/piggz/harbour-amazfish, as I took some ideas and code from there.
